version: '3.4'

services:
  

  web.client:
    image: ${DOCKER_REGISTRY-}webclient
    build:
      context: .
      dockerfile: src/Web/Client/Dockerfile


  web.server:
    image: ${DOCKER_REGISTRY-}webserver
    build:
      context: .
      dockerfile: src/Web/Server/Dockerfile


  rating.hub:
    image: ${DOCKER_REGISTRY-}ratinghub
    build:
      context: .
      dockerfile: src/Services/Rating/Rating.Hub/Dockerfile

