version: '3.4'
services:
  web.server:
    image: ${DOCKER_REGISTRY-}webserver
    build:
      context: .
      dockerfile: src/Web/Server/Dockerfile
  rating.hub:
    image: ${DOCKER_REGISTRY-}ratinghub
    build:
      context: .
      dockerfile: src/Services/Rating/Rating.Hub/Dockerfile
  postgres_image:
     image: postgres:latest
  

